### PR TITLE
Ursapolly/translation into rus

### PR DESCRIPTION
**Pull request by ursapolly**

### CODE REVIEW

**Comment by larskanis** [comment]
Привет!

Wow - I can not verify this, but it looks like a great work! 

What is your intending with this translation? Would you like to register a separate domain "rubyinstaller.ru" for it? Or is it the base for a multilingual site?

I would prefer a multilingual site with a language selector and automatic redirection to the preferred language, since I think it's better to maintain.

**Comment by installero** [comment]
Hi, thank you for appreciating our work and for rubyinstaller!

>> What is your intending with this translation? Would you like to register a separate domain "rubyinstaller.ru" for it? Or is it the base for a multilingual site?

We have already registered rubyinstaller.ru and our plan is to maintain fresh russian version of .org website for our local users, especially beginners. We have a Russian YouTube channel about Ruby/Rails and advocating for it among newcomers to programming.

We can assure you that we'll update current links to all original binaries and downloads, as well as new posts from .org site at least monthly (but will try to update new binary releases links as soon as possible).

That's the way we can afford it for now.

Hope we would be able to do more (multilingual site etc.) in future.

**Comment by larskanis** [comment]
Thank you @installero for sharing these insights! So I'm glad, that my English seems to be well enough to be understood by non native English speakers at least :thumbsup:

Let me know if I should change something or add links or whatever.

**Comment by installero** [comment]
> Let me know if I should change something or add links or whatever.

Yes, please, we would be glad to see the link from you main site and maybe news post about new localized website if you will.

**Pull request closed without merging**
